name: 专属r2s-lean-openwrt

on:
  schedule:
    - cron: 26 18 * * *
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
  ZIP_PWD: ${{ secrets.ZIP_PWD }}
  GITHUB_TOKEN: ${{ secrets.GHTOKEN }}

jobs:
  build_my_R2s:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2

      # - name: 初始化
      #   env:
      #     DEBIAN_FRONTEND: noninteractive
      #   run: |
      #     sh 1-init.sh

      - name: ffff
        run: |
          # cd lede
          bash wht.sh

      # - name: 添加额外package
      #   run: |
      #     cd lede
      #     sh 2-extraPkg.sh

      # - name: 更新feeds
      #   run: |
      #     cd lede
      #     sh 3-feeds.sh

      # - name: 预下载
      #   run: |
      #     cd lede
      #     sh 4-download.sh

      # - name: 构建
      #   run: |
      #     cd lede
      #     sh 5-build.sh

      # - name: 重打包固件
      #   run: |
      #     cd lede
      #     sh 6-repack.sh

      # - name: 上传固件
      #   run: |
      #     cd lede
      #     sh 7-upload.sh

      # - name: 发布Release
      #   run: |
      #     cd lede
      #     bash 8-release.sh

      # - name: 删除旧Releases
      #   uses: dev-drprasad/delete-older-releases@v0.1.0
      #   with:
      #     keep_latest: 10
      #     delete_tags: true

